# Database connection
spring.datasource.url=jdbc:postgresql://ep-noisy-lake-aoja408v-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_NDZI60jzBGvp
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA & Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# Gemini API Key
gemini.api.key=AIzaSyBgty6M27Eyx3Ubcz7N-qHWeZY8T9TUOJA
